version: "3.8"
services:
  nginx:
    build: "./containers/nginx"
    ports:
      - "80:80"
      - "443:443"
    container_name: "nginx"
    networks:
      - app  

  node:
    build: "./containers/node"
    container_name: "node"
    networks:
      - app
      - db
      - amqp
    environment:
      - HOST_REDIRECT
    depends_on:
      - rabbitmq

  mongodb:
    build: "./containers/mongo"
    container_name: "mongodb"
    networks:
      - db

  nodemailer:
    build: "./containers/nodemailer"
    container_name: "nodemailer"
    networks:
      - amqp
    depends_on:
      - rabbitmq
  
  rabbitmq:
    build: "./containers/rabbitmq"
    container_name: "rabbitmq"
    networks:
      - amqp

networks:
  app:
  db:
  amqp:
