version: "3.8"
services:
  nginx:
    build: "./containers/nginx"
    ports:
      - "80:80"
    container_name: "nginx"
    networks:
      - app

  node:
    build: "./containers/node"
    container_name: "node"
    networks:
      - app
      - db
      - mail

  mongodb:
    build: "./containers/mongo"
    container_name: "mongodb"
    networks:
      - db

  nodemailer:
    build: "./containers/nodemailer"
    container_name: "nodemailer"
    networks:
      - mail

networks:
  app:
  db:
  mail:
